//
// Created by jeppe on 12/4/22.
//

#ifndef RADIOACTIVE_DECAY_G4BDTRITONNEUTRONDECAY_HH
#define RADIOACTIVE_DECAY_G4BDTRITONNEUTRONDECAY_HH


class G4BDTritonNeutronDecay {

};


#endif //RADIOACTIVE_DECAY_G4BDTRITONNEUTRONDECAY_HH
